### ISSUE TITLE
不会自动生成接口,  

### ISSUE THREAD

**Issue by budaowengd** [JeremyLiao/SmartEventBus#1]
1、按照步骤添加依赖后, 不会自动生成接口,  
2、请问支持kotlin吗?

**Comment by budaowengd** [comment]
生成了代码后, 一直报错 

> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
AGPBI: {"kind":"error","text":"Program type already present: com.jeremyliao.liveeventbus.LiveEventBus$1","sources":[{}],"tool":"D8"}

> Task :app:buildInfoGeneratorDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: com.jeremyliao.liveeventbus.LiveEventBus$1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by JeremyLiao** [comment]
根据log，应该是LiveEventBus版本冲突所致，因为invoking-message依赖了LiveEventBus
首先，你可以查找一下你的工程中还有什么地方引用了“com.jeremyliao:live-event-bus”，如果找到了，删掉应该就可以解决问题了。
如果直接搜不到，也可以用gradlew  app:dependencies命令看一下依赖关系，看一下哪个库引用了“com.jeremyliao:live-event-bus”，用exclude来排除这个库对“com.jeremyliao:live-event-bus”的引用，应该就可以解决这个问题

**Comment by budaowengd** [comment]
对对对, 太感谢了.. 解决了
